apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: meu-componente
  description: Este é um componente de exemplo.
spec:
  type: service
  owner: team-a
  lifecycle: production
  definition:
    - .github/workflows/ci.yml
